### ISSUE TITLE
Trojan:Win32/Fuerboos.E!cl

### ISSUE THREAD

**Issue by InstantArcade** [QuestYouCraft/Microsoft-Store-UnInstaller#1]
Windows Defender reports this as containing **Trojan:Win32/Fuerboos.E!cl**

**Comment by QuestYouCraft** [comment]
I checked this file with [VirusTotal](https://www.virustotal.com/gui/file/3792b52fb88abff344510640390a72b8b8e2189bd0bea328501c6ec60411a029/detection) and Windows Defender with its latest updates (on Windows 10 20H2). In both cases, the virus was not found. However, I admit that over time, the reaction to this file has changed compared to 2018-11-13 (it was on this day, [according to the Microsoft report](https://docs.microsoft.com/ru-ru/windows/release-information/), the LTSC distribution was released, and, possibly, the Windows Defender offline database was older than the release date LTSC), so for now I would advise you to do the following:
- Install the latest Windows Defender updates
- Temporarily disable Windows Defender when using MSUI

For my part, I'll check this file in a Windows 10 LTSC virtual machine without an Internet connection. If you attach proof that the virus was actually found in my file, as well as the characteristics of Windows Defender (Options > About) or my scan shows that the virus was found, I will take action. Otherwise, I close this issue.

**Comment by QuestYouCraft** [comment]
It took me a long time to check the program under different conditions of Windows Defender Antivirus, but during the tests the file was never detected as malicious. Therefore, in my opinion, this issue remains invalid. If you attach proof to the contrary with the specifications, then I will continue to understand the problem. This issue will be closed.

[**[My proof (video)]**](https://drive.google.com/file/d/1QGZDB7e5LBakwhMyll8wNeIgfTxhr1ue/view)
