### ISSUE TITLE
Where to get the lastest packages needed to install MS Store?

### ISSUE THREAD

**Issue by HppZ** [QuestYouCraft/Microsoft-Store-UnInstaller#2]

**Comment by QuestYouCraft** [comment]
Microsoft Store must update itself and other apps and components (for example, Desktop App Installer) provided that you haven't disabled auto-updating of apps in the Microsoft Store settings.

**Comment by HppZ** [comment]
I mean these packages:
![image](https://user-images.githubusercontent.com/12285582/133931190-e6b4b04b-4dab-4387-9fae-6b2342548017.png)

**Comment by QuestYouCraft** [comment]
I take these packages from the Microsoft Store through this website: [store.rg-adguard.net](https://store.rg-adguard.net)

**Comment by HppZ** [comment]
how about those xml files?

**Comment by HppZ** [comment]
Do I need to update those xml files?

**Comment by QuestYouCraft** [comment]
XML files in this case are signatures. I have not updated or replaced them (because the developer is the same: Microsoft Corporation). Initially, I took the XML files from [LTSC-Add-MicrosoftStore](https://github.com/kkkgo/LTSC-Add-MicrosoftStore). In theory, packages can be installed without a signature, but I have not checked this.

**Comment by HppZ** [comment]
Thank you.
